services:
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_DATABASE: /data/mailpit.db
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT:-5432}
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST_DOCKER:-db}

volumes:
  db:
    driver: local
